name: "Check staging"
description: "Check if staging has been merged."
author: aki77
inputs:
  stagingBranch:
    description: staging branch
    default: staging
    required: false
  token:
    description: "Github token"
    required: true
runs:
  using: "node12"
  main: "dist/index.js"
