name: "Check merged"
description: "Check if it has been merged."
author: aki77
branding:
  icon: git-branch
  color: green
inputs:
  originBranch:
    description: Origin branch
    default: staging
    required: false
  token:
    description: "Github token"
    required: true
  title:
    description: "Title"
    default: "# :anger: Not merged!"
    required: false
runs:
  using: "node12"
  main: "dist/index.js"
